configs:
- id: SYNTHETIC_TEST-2FAFE4BA2C90E0D8
  config:
    name: staging_astroshop
    parameters:
      extractedIDs:
        type: value
        value:
          id_SYNTHETIC_TEST_STEP_1FEBEFACEBB72E79: SYNTHETIC_TEST_STEP-1FEBEFACEBB72E79
          id_SYNTHETIC_TEST_STEP_9A9883BB0146029C: SYNTHETIC_TEST_STEP-9A9883BB0146029C
          id_SYNTHETIC_TEST_STEP_09F42BC8FD91AA6F: SYNTHETIC_TEST_STEP-09F42BC8FD91AA6F
          id_SYNTHETIC_TEST_STEP_32DE5FF60A7A0862: SYNTHETIC_TEST_STEP-32DE5FF60A7A0862
          id_SYNTHETIC_TEST_STEP_92A93EE90254E34E: SYNTHETIC_TEST_STEP-92A93EE90254E34E
          id_SYNTHETIC_TEST_STEP_287EE08A1C5ED0F1: SYNTHETIC_TEST_STEP-287EE08A1C5ED0F1
          id_SYNTHETIC_TEST_STEP_2C01EEE926C52EBE: SYNTHETIC_TEST_STEP-2C01EEE926C52EBE
          id_SYNTHETIC_TEST_STEP_07633571E3479085: SYNTHETIC_TEST_STEP-07633571E3479085
          id_SYNTHETIC_TEST_STEP_D135717DD3AFE32F: SYNTHETIC_TEST_STEP-D135717DD3AFE32F
          id_SYNTHETIC_TEST_STEP_F7F586E85E48465A: SYNTHETIC_TEST_STEP-F7F586E85E48465A
          id_SYNTHETIC_TEST_STEP_FF7DFF984C0B1E9C: SYNTHETIC_TEST_STEP-FF7DFF984C0B1E9C
      syntheticlocation__SYNTHETIC_LOCATIONCCF8A71E8E5D6EFD__id:
        configId: SYNTHETIC_LOCATION-CCF8A71E8E5D6EFD
        configType: synthetic-location
        property: id
        type: reference
    template: SYNTHETIC_TEST-2FAFE4BA2C90E0D8.json
    skip: false
  type:
    api: synthetic-monitor
- id: SYNTHETIC_TEST-7FA55FC6FD2F3CAB
  config:
    name: gitlab
    parameters:
      extractedIDs:
        type: value
        value:
          id_67fdfef7_6381_4554_93be_a528afb0f165: 67fdfef7-6381-4554-93be-a528afb0f165
          id_SYNTHETIC_TEST_STEP_1B513AFF422375DB: SYNTHETIC_TEST_STEP-1B513AFF422375DB
          id_SYNTHETIC_TEST_STEP_23C7E6ACAAEEE6E9: SYNTHETIC_TEST_STEP-23C7E6ACAAEEE6E9
          id_SYNTHETIC_TEST_STEP_29AF39B9A9BA8F1B: SYNTHETIC_TEST_STEP-29AF39B9A9BA8F1B
          id_SYNTHETIC_TEST_STEP_2C2BB287E21BD105: SYNTHETIC_TEST_STEP-2C2BB287E21BD105
          id_SYNTHETIC_TEST_STEP_77E7DC756C71D17D: SYNTHETIC_TEST_STEP-77E7DC756C71D17D
          id_SYNTHETIC_TEST_STEP_A6FB49E90F35429B: SYNTHETIC_TEST_STEP-A6FB49E90F35429B
          id_SYNTHETIC_TEST_STEP_C4824B4E07EA76CE: SYNTHETIC_TEST_STEP-C4824B4E07EA76CE
          id_SYNTHETIC_TEST_STEP_D3FDE860BDC9FDC0: SYNTHETIC_TEST_STEP-D3FDE860BDC9FDC0
          id_SYNTHETIC_TEST_STEP_D4F73B3C04916754: SYNTHETIC_TEST_STEP-D4F73B3C04916754
          id_SYNTHETIC_TEST_STEP_D76F2992996E17E7: SYNTHETIC_TEST_STEP-D76F2992996E17E7
          id_SYNTHETIC_TEST_STEP_D1998C454FDBF79B: SYNTHETIC_TEST_STEP-D1998C454FDBF79B
          id_SYNTHETIC_TEST_STEP_DFAB3080BB33852B: SYNTHETIC_TEST_STEP-DFAB3080BB33852B
          id_SYNTHETIC_TEST_STEP_E8F9CC443A39B2DD: SYNTHETIC_TEST_STEP-E8F9CC443A39B2DD
          id_SYNTHETIC_TEST_STEP_F3364F6DA759E0A1: SYNTHETIC_TEST_STEP-F3364F6DA759E0A1
      syntheticlocation__SYNTHETIC_LOCATIONCCF8A71E8E5D6EFD__id:
        configId: SYNTHETIC_LOCATION-CCF8A71E8E5D6EFD
        configType: synthetic-location
        property: id
        type: reference
    template: SYNTHETIC_TEST-7FA55FC6FD2F3CAB.json
    skip: false
  type:
    api: synthetic-monitor
